### ISSUE TITLE
http: ContentLength=N with Body length 0

### ISSUE THREAD

**Issue by hipeace86** [asmcos/requests#10]
client:= requests.Requests()
	client.Post("https://www.httpbin.org/post",requests.Datas{"abc":"123","ddd":"789"})
	resp,err:=client.Get("https://www.httpbin.org/get")
	if err!= nil{
		fmt.Println(err)
	}
	fmt.Println(resp.Text())

**Comment by asmcos** [comment]
已经修复了 post后的残留数据
