### ISSUE TITLE
是否是并发不安全的

### ISSUE THREAD

**Issue by sirodeneko** [asmcos/requests#25]
使用requests.Requests() 创建了一个对象，并发的利用这个对象去发送请求是否会造成错误

**Comment by yuanyb** [comment]
> 使用requests.Requests() 创建了一个对象，并发的利用这个对象去发送请求是否会造成错误

@sirodeneko 肯定不是并发安全啊，看一下代码不就知道了。比如并发调用一个 `Request` 的 `Get` 方法，每个调用都会向同一个`Request` 写值，不就乱套了。
